apis/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
]

t_market/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from ddat.views import IndexView
from board.views import (
    WriteView,
    QuestionView,
    QnaView,
    BoardView,
    BoardDetailView,
    AnswerView,
    QuestionDetailView,
)
from tmuser.views import RegisterView, LoginView, logout
from notice.views import (
    NoticeView,
    NoticeDetailView,
    NoticeregisterView,
    NoticeMainView,
    AuthorizeView,
    AdminView,
    TalentMarketMainView,
    GroupMainView,
    HandcraftMainView,
    IdAuthorizationView,
)
from market.views import (
    MarketView,
    HandcraftView,
    GroupView,
    MarketDetailView,
    HandcraftDetailView,
    GroupDetailView,
    MarketRegisterView,
    WantRegisterView,
    MarketBoardDetailView,
    MarketUpdateView,
    BoardDeleteView,
    CommentDeleteView,
    MarketBoardUpdateView,
)
from apis.views import (
    ContentCreateView,
    MarketCreateView,
    WantCreateView,
    NoteCreateView,
    ReplyCreateView,
    CommentCreateView,
)
from mypage.views import (
    NoteView,
    MypageView,
    ReadNoteView,
    ReadNoteDetailView,
    NoteDeleteView,
    MypageUpdateView,
    IdVerificationView,
)

urlpatterns = [
    path("", IndexView.as_view()),
    path("admin/", admin.site.urls),
    path("board/", NoticeView.as_view()),
    path("board/<int:pk>/", BoardDetailView.as_view()),
    path("board/board/", BoardView.as_view()),
    path("board/market/", MarketView.as_view()),
    path("board/market/delete/<int:pk>", BoardDeleteView),
    path("board/market/board/comment/delete/<int:pk>", CommentDeleteView),
    path("board/market/update/<int:pk>", MarketUpdateView.as_view()),
    path("board/market/board/update/<int:pk>", MarketBoardUpdateView.as_view()),
    path("board/market/<int:pk>", MarketDetailView.as_view()),
    path("board/market/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("board/market/register/", MarketRegisterView.as_view()),
    path("board/want/register/", WantRegisterView.as_view()),
    path("board/handcraft/", HandcraftView.as_view()),
    path("board/handcraft/<int:pk>", HandcraftDetailView.as_view()),
    path("board/handcraft/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("board/group/", GroupView.as_view()),
    path("board/group/<int:pk>", GroupDetailView.as_view()),
    path("board/group/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("login/", LoginView.as_view()),
    path("register/", RegisterView.as_view()),
    path("logout/", logout),
    path("mypage/", MypageView.as_view()),
    path("mypage/verification/", IdVerificationView.as_view()),
    path("mypage/update/", MypageUpdateView.as_view()),
    path("mypage/note/", NoteView.as_view()),
    path("mypage/note/read/", ReadNoteView.as_view()),
    path("mypage/note/read/<int:user>/<int:pk>", ReadNoteDetailView.as_view()),
    path("mypage/note/delete/<int:pk>", NoteDeleteView),
    path("notice/", NoticeView.as_view()),
    path("notice/<int:pk>/", NoticeDetailView.as_view()),
    path("notice/admin/", AdminView.as_view()),
    path("notice/admin/authorize/", AuthorizeView.as_view()),
    path("notice/admin/id_check/", IdAuthorizationView.as_view()),
    path("notice/admin/register/", NoticeregisterView.as_view()),
    path("notice/admin/noticemain/", NoticeMainView.as_view()),
    path("notice/admin/talentmarketmain/", TalentMarketMainView.as_view()),
    path("notice/admin/groupmain/", GroupMainView.as_view()),
    path("notice/admin/handcraftmain/", HandcraftMainView.as_view()),
    path("write/<int:pk>", WriteView.as_view()),
    path("ask/qna/", QnaView.as_view()),
    path("ask/answer/", QuestionView.as_view()),
    path("ask/answer/<int:pk>", QuestionDetailView.as_view()),
    path("ask/answer/answer/", AnswerView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path(
        "views/contents/create/<int:pk>",
        ContentCreateView.as_view(),
        name="apis_views_content_create",
    ),
    path(
        "views/market/create/",
        MarketCreateView.as_view(),
        name="apis_views_market_create",
    ),
    path(
        "views/want/create/",
        WantCreateView.as_view(),
        name="apis_views_want_create",
    ),
    path(
        "views/note/create/",
        NoteCreateView.as_view(),
        name="apis_views_note_create",
    ),
    path(
        "views/reply/create/",
        ReplyCreateView.as_view(),
        name="apis_views_reply_create",
    ),
    path(
        "views/comment/create/",
        CommentCreateView.as_view(),
        name="apis_views_comment_create",
    ),
]

notice/models.py
import os
import uuid
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from market.models import TalentMarket, Group, Handcraft

# Create your models here.
def image_upload_to(instance, filename):
    ext = filename.split(".")[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))


class NoticeModel(models.Model):
    UPLOAD_PATH = "user-upload"

    title = models.CharField(max_length=32, verbose_name="제목")

    image = models.ImageField(upload_to=image_upload_to, blank=True)

    image_thumbnail = ImageSpecField(
        source="image", processors=[ResizeToFill(600, 480)]
    )

    content = models.TextField(verbose_name="공지 내용")

    writer = models.CharField(
        max_length=8,
        verbose_name="작성자",
    )

    registered_dttm = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")

    modified_dttm = models.DateTimeField(auto_now=True, verbose_name="수정시간")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "notice"
        verbose_name = "공지사항"
        verbose_name_plural = "공지사항"


class MainModel(models.Model):
    notice = models.ForeignKey(
        NoticeModel,
        on_delete=models.CASCADE,
        related_name="notice",
        null=True,
        blank=True,
    )

    talentmarket = models.ForeignKey(
        TalentMarket,
        on_delete=models.CASCADE,
        related_name="talentmarket",
        null=True,
        blank=True,
    )

    talentmarket_main = models.TextField(verbose_name="재능장 메인 설명", default="기본값")

    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name="group",
        null=True,
        blank=True,
    )

    group_main = models.TextField(verbose_name="소모임 메인 설명", default="기본값")

    handcraft = models.ForeignKey(
        Handcraft,
        on_delete=models.CASCADE,
        related_name="handcraft",
        blank=True,
        null=True,
    )

    handcraft_main = models.TextField(verbose_name="소공예품 메인 설명", default="기본값")

    def __str__(self):
        return self.talentmarket_main

    class Meta:
        db_table = "main"
        verbose_name = "게시판 메인"
        verbose_name_plural = "게시판 메인"

notice/forms.py
from django import forms
from .models import NoticeModel
from ddat.models import Market


class NoticeregisterForm(forms.Form):
    title = forms.CharField(
        error_messages={"required": "제목을 입력해주세요."}, label="공지 제목")
    image = forms.ImageField(required=False)
    content = forms.CharField(
        error_messages={"required": "내용을 입력해주세요."}, label="공지 내용")

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        image = cleaned_data.get("image")
        content = cleaned_data.get("content")


class AuthorizeForm(forms.Form):
    market_name = forms.CharField(
        error_messages={"required": "장/모임 이름을 선택해주세요."}, label="장/모임 이름"
    )
    authorization = forms.CharField(
        error_messages={"required": "승인여부를 확인해주세요."}, label="승인 여부"
    )

    def clean(self):
        cleaned_data = super().clean()
        market_name = cleaned_data.get("market_name")
        authorization = cleaned_data.get("authorization")


class IdAuthorizationForm(forms.Form):
    user_id = forms.CharField(
        error_messages={"required": "사용자 이름을 선택해주세요."}, label="사용자 이름"
    )
    authorization = forms.CharField(
        error_messages={"required": "승인여부를 확인해주세요."}, label="승인 여부"
    )

    def clean(self):
        cleaned_data = super().clean()
        market_name = cleaned_data.get("market_name")
        authorization = cleaned_data.get("authorization")


class NoticeMainForm(forms.Form):
    title = forms.CharField(
        error_messages={"required": "장/모임 이름을 선택해주세요."}, label="제목")
    main = forms.CharField(
        error_messages={"required": "승인여부를 확인해주세요."}, label="메인 공지")

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        main = cleaned_data.get("main")


class MarketMainForm(forms.Form):
    market_name = forms.CharField(
        error_messages={"required": "장/모임 이름을 선택해주세요."}, label="제목"
    )
    main = forms.CharField(
        error_messages={"required": "승인여부를 확인해주세요."}, label="메인 공지")

    main_content = forms.CharField(
        error_messages={"required": "메인 내용을 입력해주세요."}, label="메인 내용"
    )

    def clean(self):
        cleaned_data = super().clean()
        market_name = cleaned_data.get("market_name")
        main = cleaned_data.get("main")
        main_content = cleaned_data.get("main_content")

notice/templates/admin.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
    {% if userinfo.level == 'admin' %}
    <h1>관리자 페이지</h1>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>공지하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/register/'">공지하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>메인 공지 등록하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/noticemain/'">등록하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>장/모임 승인하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/authorize/'">승인하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>학생증 승인하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/id_check/'">학생증 승인하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>질문 답변하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/ask/answer/answer/'">답변하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>재능장 메인 등록하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/talentmarketmain/'">등록하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>공예품장 메인 등록하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/handcraftmain/'">등록하기</button>
            </div>
        </header>
    </article>
    <hr>
    <article class="post featured">
        <header class="major">
            <h3>
                <a>소모임 메인 등록하기
                </a>
            </h3>
            <div>
                <button onclick="location.href='/notice/admin/groupmain/'">등록하기</button>
            </div>
        </header>
    </article>
    <hr>
    {% endif %}
    {% endblock %}

    <!-- article -->
    {% block article %}
    {% endblock %}

notice/templates/authorize.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>장/모임 승인하기</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if markets == "None" %}
        <p>
          승인할 장/모임이 없습니다.
        </p>
        {% endif %}
        <label for="market_name" style="float: left;">재능장 선택</label>
        <select name="market_name" id="id_market_name">
          {% for market in markets %}
          {% if market.admin.id_verification == "Y" %}
          <option value="{{ market.market_name }}">{{ market.market_name }}</option>
          {% endif %}
          {% endfor %}
        </select>
        <br />
        <label for="authorization" style="float: left;">승인 여부</label>
        <select name="authorization" id="id_authorization">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

notice/templates/group_main.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>메인 소모임</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if markets == "None" %}
        <p>
          메인으로 할 소모임이 없습니다.
        </p>
        {% endif %}
        <label for="market_name" style="float: left;">공지 선택</label>
        <select name="market_name" id="id_market_name">
          {% for market in markets %}
          <option value="{{ market.market_name }}">{{ market.market_name }}</option>
          {% endfor %}
        </select>
        <br />
        <label for="id_main" style="float: left;">메인 여부</label>
        <select name="main" id="id_main">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>
        <label for="id_main_content">메인 내용</label>
        <textarea class="form-control" id="id_main_content" name="main_content" placeholder="메인 소모임 내용"></textarea>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

notice/templates/handcraft_main.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>메인 공예품장</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if markets == None %}
        <p>
          메인으로 할 공예품장이 없습니다.
        </p>
        {% endif %}
        <label for="market_name" style="float: left;">공지 선택</label>
        <select name="market_name" id="id_market_name">
          {% for market in markets %}
          <option value="{{ market.market_name }}">{{ market.market_name }}</option>
          {% endfor %}
        </select>
        <br />
        <label for="id_main" style="float: left;">메인 여부</label>
        <select name="main" id="id_main">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>
        <label for="id_main_content">메인 내용</label>
        <textarea class="form-control" id="id_main_content" name="main_content" placeholder="메인 공예품장 내용"></textarea>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

notice/templates/id_authorization.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>학생증 승인하기</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if users == "None" %}
        <p>
          승인할 학생증이 없습니다.
        </p>
        {% endif %}
        <label for="user_id" style="float: left;">사용자 선택</label>
        <select name="user_id" id="user_id" class="form-control">
          {% for user in users %}
          <option value="{{ user.id }}">
            {{ user }}
          </option>
          {% endfor %}
        </select>
        <br />
        {% for user in users %}
        <div class="image-wrapper">
          <div class="image">
            <div style="text-align: left; font-size: 1rem;">
              {{ user.waiting_user.username }}
            </div>
            <img src="{{ user.waiting_user.id_image.url }}" />
          </div>
        </div><br>
        {% endfor %}
        <label for="authorization" style="float: left;">승인 여부</label>
        <select name="authorization" id="authorization" class="form-control">
          <option value="Y">Y</option>
          <op xtion value="N">N</option>
        </select>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

  {% block script %}
  {% endblock %}

notice/templates/notice.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<article class="post featured">
  <header class="major">
    <h2><a> 공지사항 </a></h2>
    <hr>
    <div style="text-align: left; border: 1px solid;">
      <div style="display: block; padding: 2rem 2rem 1rem 2rem; border: 0.1px; margin-right: -4px;">
        <div style="text-align: center; font-size: 1.1rem; font-weight: bold;">
          {{ notice_main.notice.title }}
        </div>
        <hr>
        <div style="text-align: center; margin: auto;">
          <a class="image main" href="/notice/{{ notice_main.notice.id }}"><img
              src="{{ notice_main.notice.image.url }}" /></a><br>
        </div>
        <hr>
        <div style="text-align: left;">
          <pre>{{ notice_main.notice.content }}</pre>
        </div>
      </div>
    </div>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
<article class="post featured">
  <header class="major">
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>제목</th>
            <th>작성자</th>
            <th>작성날짜</th>
          </tr>
        </thead>
        <tbody>
          {% for notice in notices %}
          <tr>

            <th><a href="/notice/{{ notice.id }}">{{ notice.title }}</a></th>
            <th><a href="/notice/{{ notice.id }}">{{ notice.writer }}</a></th>
            <th>{{ notice.registered_dttm|date:'Y-m-d' }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </header>
</article>
{% endblock %}

notice/templates/notice_detail.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<article class="post featured">
  <header class="major">
    <h2><a> {{ notice.title }} </a></h2>
    <hr>
    <div class="image-wrapper">
      <div class="image">
        {% if notice.image %}
        <a class="image main"><img src="{{ notice.image.url }}" /></a>
        {% endif %}
        <div style="text-align: left; font-size: 1rem;">
          <pre>{{ notice.content }}</pre>
        </div>
      </div>
    </div>
    <hr>
    <div class="button" style="float: right;"><a href="/notice/" class="none">돌아가기</a></div>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
{% endblock %}

notice/templates/notice_main.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>메인 공지 등록</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if notices == None %}
        <p>
          메인 공지할 공지가 없습니다.
        </p>
        {% endif %}
        <label for="title" style="float: left;">공지 선택</label>
        <select name="title" id="id_title">
          {% for notice in notices %}
          <option value="{{ notice.title }}">{{ notice.title }}</option>
          {% endfor %}
        </select>
        <br />
        <label for="main" style="float: left;">메인 여부</label>
        <select name="main" id="id_main">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

notice/templates/notice_register.html
{% extends "write_base.html" %}

<!-- 스타일 -->
{% block style %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
  $(document).ready(function () {
    $('#id_content').summernote({
      height: 300
    });
  }); 
</script>
{% endblock %}

<!-- 메인 -->

{% block main %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>공지하기</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}" style="float: left;">{{ field.label }}</label>
        {% ifequal field.name 'content' %}
        <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
        {% else %}
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}">
        {% endifequal %}
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <ul class="actions" style="float: right;">
        <li><input type="submit" value="공지하기" class="right" /></li>
      </ul>
    </form>
  </div>
</div><br>
<div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
{% endblock %}

notice/templates/talentmarket_main.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>공지사항</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>메인 재능장 등록</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if markets == None %}
        <p>
          메인으로 할 재능장이 없습니다.
        </p>
        {% endif %}
        <label for="market_name" style="float: left;">공지 선택</label>
        <select name="market_name" id="id_market_name">
          {% for market in markets %}
          <option value="{{ market.market_name }}">{{ market.market_name }}</option>
          {% endfor %}
        </select>
        <br />
        <label for="id_main" style="float: left;">메인 여부</label>
        <select name="main" id="id_main">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>
        <label for="id_main_content">메인 내용</label>
        <textarea class="form-control" id="id_main_content" name="main_content" placeholder="메인 재능장 내용"></textarea>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/notice/admin/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}