apis/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
]

board/urls.py
from django.urls import path, include
from . import views

urlpatterns = []

t_market/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from ddat.views import IndexView
from board.views import (
    WriteView,
    QuestionView,
    QnaView,
    BoardView,
    BoardDetailView,
    AnswerView,
    QuestionDetailView,
)
from tmuser.views import RegisterView, LoginView, logout
from notice.views import (
    NoticeView,
    NoticeDetailView,
    NoticeregisterView,
    NoticeMainView,
    AuthorizeView,
    AdminView,
    TalentMarketMainView,
    GroupMainView,
    HandcraftMainView,
    IdAuthorizationView,
)
from market.views import (
    MarketView,
    HandcraftView,
    GroupView,
    MarketDetailView,
    HandcraftDetailView,
    GroupDetailView,
    MarketRegisterView,
    WantRegisterView,
    MarketBoardDetailView,
    MarketUpdateView,
    BoardDeleteView,
    CommentDeleteView,
    MarketBoardUpdateView,
)
from apis.views import (
    ContentCreateView,
    MarketCreateView,
    WantCreateView,
    NoteCreateView,
    ReplyCreateView,
    CommentCreateView,
)
from mypage.views import (
    NoteView,
    MypageView,
    ReadNoteView,
    ReadNoteDetailView,
    NoteDeleteView,
    MypageUpdateView,
    IdVerificationView,
)

urlpatterns = [
    path("", IndexView.as_view()),
    path("admin/", admin.site.urls),
    path("board/", NoticeView.as_view()),
    path("board/<int:pk>/", BoardDetailView.as_view()),
    path("board/board/", BoardView.as_view()),
    path("board/market/", MarketView.as_view()),
    path("board/market/delete/<int:pk>", BoardDeleteView),
    path("board/market/board/comment/delete/<int:pk>", CommentDeleteView),
    path("board/market/update/<int:pk>", MarketUpdateView.as_view()),
    path("board/market/board/update/<int:pk>", MarketBoardUpdateView.as_view()),
    path("board/market/<int:pk>", MarketDetailView.as_view()),
    path("board/market/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("board/market/register/", MarketRegisterView.as_view()),
    path("board/want/register/", WantRegisterView.as_view()),
    path("board/handcraft/", HandcraftView.as_view()),
    path("board/handcraft/<int:pk>", HandcraftDetailView.as_view()),
    path("board/handcraft/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("board/group/", GroupView.as_view()),
    path("board/group/<int:pk>", GroupDetailView.as_view()),
    path("board/group/detail/<int:market>/<int:pk>",
         MarketBoardDetailView.as_view()),
    path("login/", LoginView.as_view()),
    path("register/", RegisterView.as_view()),
    path("logout/", logout),
    path("mypage/", MypageView.as_view()),
    path("mypage/verification/", IdVerificationView.as_view()),
    path("mypage/update/", MypageUpdateView.as_view()),
    path("mypage/note/", NoteView.as_view()),
    path("mypage/note/read/", ReadNoteView.as_view()),
    path("mypage/note/read/<int:user>/<int:pk>", ReadNoteDetailView.as_view()),
    path("mypage/note/delete/<int:pk>", NoteDeleteView),
    path("notice/", NoticeView.as_view()),
    path("notice/<int:pk>/", NoticeDetailView.as_view()),
    path("notice/admin/", AdminView.as_view()),
    path("notice/admin/authorize/", AuthorizeView.as_view()),
    path("notice/admin/id_check/", IdAuthorizationView.as_view()),
    path("notice/admin/register/", NoticeregisterView.as_view()),
    path("notice/admin/noticemain/", NoticeMainView.as_view()),
    path("notice/admin/talentmarketmain/", TalentMarketMainView.as_view()),
    path("notice/admin/groupmain/", GroupMainView.as_view()),
    path("notice/admin/handcraftmain/", HandcraftMainView.as_view()),
    path("write/<int:pk>", WriteView.as_view()),
    path("ask/qna/", QnaView.as_view()),
    path("ask/answer/", QuestionView.as_view()),
    path("ask/answer/<int:pk>", QuestionDetailView.as_view()),
    path("ask/answer/answer/", AnswerView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path(
        "views/contents/create/<int:pk>",
        ContentCreateView.as_view(),
        name="apis_views_content_create",
    ),
    path(
        "views/market/create/",
        MarketCreateView.as_view(),
        name="apis_views_market_create",
    ),
    path(
        "views/want/create/",
        WantCreateView.as_view(),
        name="apis_views_want_create",
    ),
    path(
        "views/note/create/",
        NoteCreateView.as_view(),
        name="apis_views_note_create",
    ),
    path(
        "views/reply/create/",
        ReplyCreateView.as_view(),
        name="apis_views_reply_create",
    ),
    path(
        "views/comment/create/",
        CommentCreateView.as_view(),
        name="apis_views_comment_create",
    ),
]

board/models.py
import os
import uuid
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail, ResizeToFit
from tmuser.models import Tmuser
from ddat.models import Market

# Create your models here.


class Questions(models.Model):
    username = models.CharField(max_length=32, verbose_name="이름")

    usernickname = models.CharField(max_length=32, verbose_name="닉네임")

    useremail = models.EmailField(max_length=128, verbose_name="이메일")

    phonenumber = models.CharField(
        max_length=16, verbose_name="연락처", default="기본값")

    department_name = models.CharField(max_length=64, verbose_name="학과")

    student_number = models.CharField(max_length=8, verbose_name="학번")

    title = models.CharField(max_length=32, verbose_name="제목")

    content = models.TextField(verbose_name="질문 내용")

    answered = models.CharField(
        max_length=4, verbose_name="답변 여부", default="N")

    registered_dttm = models.DateTimeField(
        auto_now_add=True, verbose_name="등록시간")

    modified_dttm = models.DateTimeField(auto_now=True, verbose_name="수정시간")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "questions"
        verbose_name = "사용자 문의사항"
        verbose_name_plural = "사용자 문의사항"


class Answer(models.Model):
    question = models.ForeignKey(
        Questions, on_delete=models.CASCADE, related_name="answer"
    )

    title = models.CharField(max_length=32, verbose_name="답변 제목")

    content = models.TextField(verbose_name="답변 내용")

    registered_dttm = models.DateTimeField(
        auto_now_add=True, verbose_name="등록시간")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "answer"
        verbose_name = "문의 답변"
        verbose_name_plural = "문의 답변"


class Content(models.Model):
    title = models.CharField(max_length=64, verbose_name="제목")

    description = models.TextField(verbose_name="설명", default="")

    writer = models.CharField(max_length=8, verbose_name="작성자")

    registered_dttm = models.DateTimeField(
        auto_now_add=True, verbose_name="등록시간")

    modified_dttm = models.DateTimeField(auto_now=True, verbose_name="수정시간")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "content"
        verbose_name = "내용"
        verbose_name_plural = "내용"


def image_upload_to(instance, filename):
    ext = filename.split(".")[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))


class Image(models.Model):
    UPLOAD_PATH = "user-upload"

    content = models.ForeignKey(Content, on_delete=models.CASCADE, null=True)
    image = ProcessedImageField(
        upload_to=image_upload_to,
        processors=[ResizeToFit(width=2048, upscale=False)],
        format='JPEG',
        options={'quality': 70},
        blank=True)

    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(200, 150)],
        format='JPEG',
    )

    market = models.ForeignKey(
        Market, on_delete=models.CASCADE, related_name="board", null=True
    )
    order = models.SmallIntegerField()

    class Meta:
        ordering = ["order"]


class Comment(models.Model):
    board = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    writer = models.ForeignKey(Tmuser, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="댓글 내용")
    registered_dttm = models.DateTimeField(
        auto_now_add=True, verbose_name="등록시간")
    modified_dttm = models.DateTimeField(auto_now=True, verbose_name="수정시간")

    def __str(self):
        return self.board

    class Meta:
        db_table = "comment"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

board/forms.py
from django import forms
from .models import Content, Questions, Answer


class WritingForm(forms.Form):
    title = forms.CharField(
        error_messages={"required": "제목을 입력해주세요."}, max_length=64, label="글 제목"
    )
    image = forms.ImageField(required=False)
    description = forms.CharField(
        error_messages={"required": "내용을 입력해주세요."}, label="내용"
    )

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        image = cleaned_data.get("image")
        description = cleaned_data.get("description")


class QuestionForm(forms.Form):
    title = forms.CharField(
        error_messages={"required": "제목을 입력해주세요."}, label="질문 제목"
    )
    content = forms.CharField(error_messages={"required": "내용을 입력해주세요."}, label="질문 내용")

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        content = cleaned_data.get("content")


class AnswerForm(forms.Form):
    question = forms.CharField(error_messages={"required": "내용을 입력해주세요."}, label="질문")

    title = forms.CharField(
        error_messages={"required": "제목을 입력해주세요."}, max_length=64, label="답변 제목"
    )
    content = forms.CharField(error_messages={"required": "내용을 입력해주세요."}, label="답변 내용")

    def clean(self):
        cleaned_data = super().clean()
        question = cleaned_data.get("question")
        title = cleaned_data.get("title")
        content = cleaned_data.get("content")

board/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import Http404
from django.db import transaction
from ddat.decorator import login_required, admin_required
from ddat.models import Market, Wants
from tmuser.models import Tmuser
from market.models import TalentMarket
from .models import Content, Questions, Image, Answer
from .forms import WritingForm, QuestionForm, AnswerForm
from django.core.mail import EmailMessage

# Create your views here.
class BoardDetailView(DetailView):
    template_name = "board_detail.html"
    queryset = Image.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["content"] = Image.objects.filter(content_id=self.kwargs["pk"])
        return context


class BoardView(TemplateView):

    template_name = "board.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["images"] = Image.objects.all()

        return context


@method_decorator(login_required, name="dispatch")
class WriteView(FormView):
    template_name = "write.html"
    form_class = WritingForm
    success_url = "/write/"

    def form_valid(self, form):
     userinfo = Tmuser.objects.get(useremail=self.request.session.get("user"))
     market = Market.objects.get(id=pk)
     title = form.data.get("title"),
     content = Content.objects.create(
         title=form.data.get("title"),
         description=form.data.get("description"),
         writer=userinfo.usernickname,
     )

     Image.objects.create(content=content, market=market, order=idx)

     return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        market = Market.objects.get(id=self.kwargs["pk"])
        context["market"] = market

        return context


class QnaView(TemplateView):
    template_name = "q&a.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.session.get("user") != None:
            context["userinfo"] = Tmuser.objects.get(
                useremail=self.request.session.get("user")
            )
            return context

        else:
            return context


class QuestionView(FormView):
    template_name = "ask_answer.html"
    form_class = QuestionForm
    success_url = "/ask/answer/"

    def form_valid(self, form):
        if self.request.session.get("user") != None:
            userinfo = Tmuser.objects.get(useremail=self.request.session.get("user"))
            title=form.data.get("title")
            content=form.data.get("content")
            questions = Questions(
                username=userinfo.username,
                usernickname=userinfo.usernickname,
                useremail=userinfo.useremail,
                phonenumber=userinfo.phonenumber,
                department_name=userinfo.department_name,
                student_number=userinfo.student_number,
                title=title,
                content=content,
                answered="N",
            )
            questions.save()

            subject = f"새 질문이 들어왔습니다. {userinfo.username}, {title}"
            message = f"{content} \n https://www.ourtalentmarket.com/admin"
            mail = EmailMessage(subject, message, to=["rlarhksrud14@gmail.com"])
            mail.send()

            messages.success(self.request, '질문이 등록되었습니다.')

            return super().form_valid(form)

        else:
            title=form.data.get("title")
            content=form.data.get("content")
            questions = Questions(
                username="가입되지 않은 사용자",
                usernickname="익명",
                useremail="anonymous@anonymous.com",
                phonenumber="010-0000-0000",
                department_name="아무개 학과",
                student_number="00000000",
                title=title,
                content=content,
                answered="N",
            )
            questions.save()

            subject = f"새 질문이 들어왔습니다. 가입되지 않은 사용자, {title}"
            message = f"{content} \n https://www.ourtalentmarket.com/admin"
            mail = EmailMessage(subject, message, to=["rlarhksrud14@gmail.com"])
            mail.send()

            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.session.get("user") != None:
            context["userinfo"] = Tmuser.objects.get(
                useremail=self.request.session.get("user")
            )
            context["questions"] = Questions.objects.all()
            return context

        else:
            context["questions"] = Questions.objects.all()
            return context


class QuestionDetailView(TemplateView):
    template_name = "ask_answer_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        questions = Questions.objects.filter(id=self.kwargs["pk"])
        answers = Answer.objects.filter(question=Questions.objects.get(id=self.kwargs["pk"]))

        context["questions"] = questions
        context["answers"] = answers

        return context

@method_decorator(admin_required, name="dispatch")
class AnswerView(FormView):
    template_name = "answer_detail.html"
    form_class = AnswerForm
    success_url = "/ask/answer/answer/"

    def form_valid(self, form, **kwargs):
        with transaction.atomic():
            userinfo = Tmuser.objects.get(useremail=self.request.session.get("user"))
            question=Questions.objects.get(id=form.data.get("question"))
            answer = Answer(
                question=question,
                title=form.data.get("title"),
                content=form.data.get("content"),
            )
            answer.save()

            question.answered = "Y"
            question.save()

            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["userinfo"] = Tmuser.objects.get(
            useremail=self.request.session.get("user")
        )
        context["questions"] = Questions.objects.all()
        context["answers"] = Answer.objects.all()
        return context

board/templates/answer.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>질문 답변</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>질문 답변</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if questions == None %}
        <p>
          답변 할 질문이 없습니다.
        </p>
        {% endif %}
        <label for="question" style="float: left;">질문 선택</label>
        <select name="question" id="id_question">
          {% for question in questions %}
          {% if question.answered == "N" %}
          <option value="{{ question.title }}">{{ question.title }}</option>
          {% endif %}
          {% endfor %}
        </select>
        <br />
        <label for="id_title" style="float: left;">답변 제목</label>
        <input type="text" class="form-control" id="id_title" name="title" placeholder="답변 제목"><br>
        <label for="id_content">답변 내용</label>
        <textarea class="form-control" id="id_content" name="content" placeholder="답변 내용"></textarea><br>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/ask/answer/answer/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

board/templates/answer_detail.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>질문 답변</h1>
{% endblock %}

<!-- 메인 -->

{% block main %}
<header class="major">
  <article class="post featured">
    <h2>질문 답변</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if questions == None %}
        <p>
          답변 할 질문이 없습니다.
        </p>
        {% endif %}
        <label for="question" style="float: left;">질문 선택</label>
        <select name="question" id="id_question">
          {% for question in questions %}
          {% if question.answered == "N" %}
          <option value="{{ question.id }}">{{ question.title }}</option>
          {% endif %}
          {% endfor %}
        </select>
        <br />
        <label for="id_title" style="float: left;">답변 제목</label>
        <input type="text" class="form-control" id="id_title" name="title" placeholder="답변 제목"><br>
        <label for="id_content">답변 내용</label>
        <textarea class="form-control" id="id_content" name="content" placeholder="답변 내용"></textarea><br>
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      <input type="submit" value="제출">
    </form>
  </article>
  <div class="button" style="float: right;"><a href="/ask/answer/answer/" class="none">돌아가기</a></div>
  {% endblock %}

  <!-- article -->
  {% block article %}
  {% endblock %}

board/templates/ask_answer.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>Q&A</h1>
<p>
  자주 묻는 질문
</p>
{% endblock %}

<!-- 메인 -->

{% block main %}
<article class="post featured">
    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                [{{ message.tags }}]
                [{{ message.message }}]
                </div>
        {% endfor %}
        </div><br>
    {% endif %}
  <header class="major">
    <h2>
      <a>질문하기
      </a>
    </h2>
    <div class="instruction" style="padding: 3rem;">
      <div class="row mt-5">
        <div class="col-12">
          <div class="text-muted" style="text-align:left; font-size: 90%;">
              로그아웃해서 질문하면 익명질문이 가능합니다.
          </div><br>
          <form method="POST" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}" style="float: left;">{{ field.label }}</label>
              {% ifequal field.name 'content' %}
              <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"
                style="height: 10rem;"></textarea>
              {% else %}
              <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                placeholder="{{ field.label }}" name="{{ field.name }}">
              {% endifequal %}
            </div><br />
            {% if field.errors %}
            <span style="color: red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <ul class="actions" style="float: right;">
              <li><input type="submit" value="질문하기" class="left" /></li>
            </ul>
          </form>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-12">
          {{ error }}
        </div>
      </div>
    </div>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
<!--답변 완료 -->
<article class="post featured">
  <header class="major">
    <h2><a> 질문 답변 </a></h2><br>
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>답변</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일자</th>
          </tr>
        </thead>
        <tbody>
          {% for question in questions %}
          {% if question.answered == "Y" %}
          <tr>
            <th><a href="/ask/answer/{{ question.id }}">답변 보기</a></th>
            <th>{{ question.title }}</th>
            <th>{{ question.usernickname }}</th>
            <th>{{ question.registered_dttm|date:'Y-m-d' }}</th>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </header>

<hr>

<!--답변 대기중 -->
<article class="post featured">
  <header class="major">
    <h2><a> 답변대기중인 질문 </a></h2><br>
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일자</th>
          </tr>
        </thead>
        <tbody>
          {% for question in questions %}
          {% if question.answered == "N" %}
          <tr>
            <th>{{ question.title }}</th>
            <th>{{ question.usernickname }}</th>
            <th>{{ question.registered_dttm|date:'Y-m-d' }}</th>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </header>
</article>
{% endblock %}

board/templates/ask_answer_detail.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

{% block intro %}
<h1>Q&A</h1>
<p>
  자주 묻는 질문
</p>
{% endblock %}

<!-- 메인 -->

{% block main %}
<article class="post featured">
  <header class="major">
    {% for question in questions %}
    <h2><a>Q.{{ question.title }}</a></h2>
    <div style="text-align: right;">
      {{ question.registered_dttm }}
    </div>
    <hr style="margin-top: 1rem;">
    <div style="text-align: left; font-size: 1rem;">
      <pre>{{ question.content }}</pre>
    </div>
    {% endfor %}
    <hr>
    {% for answer in answers %}
    <h2><a>A.{{ answer.title }}</a></h2>
    <div style="text-align: right;">
      {{ answer.registered_dttm }}
    </div>
    <hr style="margin-top: 1rem;">
    <div style="text-align: left; font-size: 1rem;">
      <pre>{{ answer.content }}</pre>
    </div>
    {% endfor %}
    <a href="/ask/answer/" class="none"><div class="button" style="float: right;">돌아가기</div></a>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
{% endblock %}

board/templates/board.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

<!-- 메인 -->

{% block main %}
<article class="post featured">
  <header class="major">
    <h2><a> 게시글 </a></h2><br>
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>제목</th>
            <th>내용</th>
            <th>작성자</th>
          </tr>
        </thead>
        <tbody>
          {% for image in images %}
          <tr>
            <th>{{ image.content.title }}</th>
            <th><a href="/board/{{ image.id }}">{{ image.content.description }}</a></th>
            <th>{{ image.content.writer }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
<article class="post featured">
  <header class="major">
    <h2><a> 게시글 </a></h2>
    <div style="text-align: left;">
      {% for image in images %}
      <div style="display: inline-block; padding: 1rem 2rem 1rem 2rem; border: 0.1px; margin-right: -4px;">
        <div style="text-align: left; font-size: 1.1rem; font-weight: bold; padding-bottom: 0.5rem;">
          {{ image.content.title }}
        </div>
        <a href="/board/{{ image.id }}"><img src="{{ image.image_thumbnail.url }}" /></a><br>
        <div style="text-align: left;">
          {{ image.content.description }}
        </div>
      </div>
      {% endfor %}
    </div>
  </header>
</article>
{% endblock %}

board/templates/board_detail.html
{% extends "write_base.html" %}

<!-- 화면 첫 부분 -->

<!-- 메인 -->

{% block main %}
<article class="post featured">
  <header class="major">
    <h2><a> {{ image.content.title }} </a></h2>
    <hr>
    <div class="image-wrapper">
      <div class="image">
        <img src="{{ image.image.url }}" />
        <div style="text-align: left; font-size: 1rem;">
          {{ image.content.description }}
        </div>
      </div>
    </div><br>
    <div class="button"><a href="/board/board/">돌아가기</a></div>
  </header>
</article>
{% endblock %}

<!-- article -->
{% block article %}
{% endblock %}

board/templates/write.html
{% extends "write_base.html" %}

<!-- 스타일 -->
{% block style %}
<link rel="stylesheet" href="/static/css/dropzone.css" />
<script src="/static/js/dropzone.js"></script>
{% endblock %}

<!-- 메인 -->

{% block main %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>글쓰기</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <div class="form-group">
      <label for="title" style="float: left;">글 제목</label>
      <input type="text" class="form-control" name="title" id="title" />
    </div>
    <div class="form-group">
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
    </div>
    <label for="image" style="float: left;">사진(1장)</label><br>
    <div class="text-muted" style="display: inline; font-size: 90%;">
      사진파일은 jpeg, jpg, png, gif 파일만 업로드 가능하며, 512kb까지 업로드 가능합니다.
    </div>
    <form method="POST" action="/views/contents/create/{{ market.id }}" class="dropzone" id="uploader"
      enctype="multipart/form-data">
      {% csrf_token %}
      <div class="dz-message" data-dz-message><span>드래그 드랍하거나, 클릭하여 이미지를 선택해주세요.</span></div>
      <div class="fallback">
        <input name="file" type="name" />
      </div>
    </form>
    <a href=" https://heictojpg.com/" target="_blank" class="none" style="font-size: 12px;">
      <div style="border: 1px solid; text-align: center; width: 100%; margin-bottom: 8px;">HEIC파일(애플
        이미지) 변환하기 </div>
    </a>
    <a href="https://blogsearch.kr/resize/" target="_blank" class="none" style="font-size: 12px;">
      <div style="border: 1px solid; text-align: center; width: 100%;">사진 크기 줄이기</div>
    </a><br>
    <div class="form-group">
      <label for="description" style="float: left;">내용</label>
      <textarea class="form-control" name="description" id="description" style="height: 10rem;"></textarea>
    </div>
    <br>
    <div style="text-align: right;">
      <input type="submit" class="btn" id="upload" value="글쓰기">
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>

  Dropzone.autoDiscover = false;

  var dropZoneUploader = new Dropzone('form#uploader', {
    init: function () {
      var dropzone = this;

      $('#upload').click(function () {
        if (dropZoneUploader.files.length) {
            dropZoneUploader.processQueue(); // upload files and submit the form
        } else {
            $.ajax({
              type: 'POST',
              url: "/views/contents/create/{{ market.id }}",
              data: {
                  csrfmiddlewaretoken: '{{ csrf_token }}',
                  title: $('#title').val(),
                  description: $('#description').val(),
              },
              success: function () {
                history.back()
              },
              error: function (e) {
                console.log(e)
                alert('에러가 발생했습니다. 파일 형식과 크기를 확인해주세요.')
              },
            });
        }
      });

      dropzone.on("sending", function (file, xhr, formData) {
        formData.append("title", $('#title').val());
        formData.append("description", $('#description').val());
      });
    },
    parallelUploads: 10,
    autoProcessQueue: false,
    type: 'POST',
    success: function () {
      history.back()
    },
    error: function (e) {
      console.log(e)
      alert('에러가 발생했습니다. 파일 형식과 크기를 확인해주세요.')
    },
    acceptedFiles: ".jpeg,.jpg,.png,.gif",
    maxFilesize: 0.5,
    addRemoveLinks: true,
    dictRemoveFile: '삭제',
    maxFiles: 1,
  });

</script>
{% endblock %}